# Generated by Django 5.1.7 on 2025-03-07 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='first_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
