# Generated by Django 5.1.7 on 2025-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_alter_visitors_first_visit_alter_visitors_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='static_trust_score',
            field=models.IntegerField(default=50),
        ),
    ]
