# Generated by Django 5.1.7 on 2025-03-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_userbehavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouseBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('mouse_speed', models.FloatField()),
                ('mouse_acceleration', models.FloatField()),
                ('click_variance', models.FloatField()),
                ('is_legitimate', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
